"use client";

import React from 'react';
import { Play, Settings, Sliders, Layers, BookOpen, Volume2, FastForward, Plus } from 'lucide-react';
import { motion } from 'motion/react';

export const PilotPhrases = () => {
  return (
    <section className="py-24 bg-white text-[#003049] relative overflow-hidden">
      {/* Abstract Background Elements */}
      <div className="absolute top-0 left-0 w-full h-full overflow-hidden pointer-events-none">
        <div className="absolute top-20 left-10 w-64 h-64 bg-blue-50 rounded-full blur-3xl opacity-60" />
        <div className="absolute bottom-20 right-10 w-96 h-96 bg-blue-100 rounded-full blur-3xl opacity-40" />
      </div>

      <div className="container mx-auto px-4 md:px-6 relative z-10">
        <div className="grid lg:grid-cols-2 gap-12 lg:gap-16 items-center">
          
          {/* Left Content: Description */}
          <div className="space-y-6 md:space-y-8">
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
            >
              <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-blue-50 text-[#003049] font-semibold text-sm mb-4 md:mb-6">
                <BookOpen className="w-4 h-4" />
                <span>Exclusive AI Training</span>
              </div>
              <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold tracking-tight mb-4 md:mb-6 font-montserrat leading-tight">
                Precision Listening & <br />
                <span className="text-blue-600">Scenario Building</span>
              </h2>
              <p className="text-base md:text-lg text-slate-600 leading-relaxed">
                Train with exact, book-standard phraseology (e.g., A220) generated by advanced AI. 
                Customize your listening experience with adjustable speeds and diverse voice options to master every nuance before you repeat it.
              </p>
            </motion.div>

            <motion.div 
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: 0.2, duration: 0.6 }}
              className="space-y-3 md:space-y-4"
            >
              {[
                { icon: Sliders, title: "Smart Playback Control", desc: "Slow down complex instructions and choose from multiple AI voices." },
                { icon: Layers, title: "Custom Scenario Builder", desc: "Combine sentences to create unique situations or find exact book scenarios." },
                { icon: BookOpen, title: "Standardized Phraseology", desc: "Learn the exact wording for specific aircraft types like the A220." }
              ].map((feature, idx) => (
                <div key={idx} className="flex items-start gap-4 p-3 md:p-4 rounded-xl hover:bg-slate-50 transition-colors duration-300">
                  <div className="w-10 h-10 md:w-12 md:h-12 rounded-lg bg-[#003049] text-white flex items-center justify-center shrink-0 shadow-lg">
                    <feature.icon className="w-5 h-5 md:w-6 md:h-6" />
                  </div>
                  <div>
                    <h3 className="font-bold text-base md:text-lg mb-1 font-montserrat">{feature.title}</h3>
                    <p className="text-slate-600 text-sm">{feature.desc}</p>
                  </div>
                </div>
              ))}
            </motion.div>

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: 0.4 }}
              className="pt-4"
            >
              <button className="w-full md:w-auto bg-[#003049] text-white px-8 py-4 rounded-full font-bold text-lg shadow-xl hover:shadow-2xl hover:bg-blue-600 hover:scale-105 transition-all duration-300 flex items-center justify-center gap-2 cursor-pointer">
                Build Your Scenario
                <Settings className="w-5 h-5" />
              </button>
            </motion.div>
          </div>

          {/* Right Content: Modern Visual Representation */}
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            whileInView={{ opacity: 1, scale: 1 }}
            viewport={{ once: true }}
            transition={{ duration: 0.8 }}
            className="relative mt-8 lg:mt-0"
          >
            {/* Main Card - Audio Player / Builder Interface */}
            <div className="relative z-10 bg-white rounded-3xl shadow-2xl border border-slate-100 overflow-hidden mx-auto max-w-md lg:max-w-none">
              {/* Header */}
              <div className="bg-[#003049] p-4 md:p-6 text-white flex justify-between items-center">
                <div className="flex items-center gap-3">
                  <div className="w-8 h-8 md:w-10 md:h-10 rounded-full bg-white/10 flex items-center justify-center">
                    <Layers className="w-4 h-4 md:w-5 md:h-5" />
                  </div>
                  <div>
                    <h3 className="font-bold text-sm md:text-base">Custom Scenario #42</h3>
                    <p className="text-[10px] md:text-xs text-blue-200">A220 • Engine Failure • Departure</p>
                  </div>
                </div>
                <Settings className="w-5 h-5 text-blue-200 cursor-pointer hover:text-white" />
              </div>

              {/* Body - Sentence Stack */}
              <div className="p-4 md:p-6 space-y-3 bg-slate-50/50 min-h-[250px] md:min-h-[300px]">
                {/* Active Sentence */}
                <div className="bg-white p-3 md:p-4 rounded-xl shadow-md border-l-4 border-blue-500 flex gap-3 md:gap-4 items-center">
                  <div className="w-8 h-8 rounded-full bg-blue-100 text-blue-600 flex items-center justify-center shrink-0">
                    <Volume2 className="w-4 h-4" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="font-medium text-slate-800 text-sm md:text-base truncate">&quot;Mayday, Mayday, Mayday...&quot;</p>
                    <div className="flex items-center gap-4 mt-2">
                      <div className="h-1 flex-1 bg-slate-100 rounded-full overflow-hidden">
                        <motion.div 
                          className="h-full bg-blue-500"
                          animate={{ width: ["0%", "100%"] }}
                          transition={{ duration: 3, repeat: Infinity }}
                        />
                      </div>
                      <span className="text-xs font-mono text-slate-400">0:03</span>
                    </div>
                  </div>
                </div>

                {/* Next Sentences */}
                <div className="bg-white p-3 md:p-4 rounded-xl border border-slate-100 opacity-60 flex gap-3 md:gap-4 items-center">
                   <div className="w-8 h-8 rounded-full bg-slate-100 text-slate-400 flex items-center justify-center shrink-0">
                    <span className="text-xs font-bold">2</span>
                  </div>
                  <p className="font-medium text-slate-500 text-sm md:text-base line-clamp-1">&quot;Request immediate return...&quot;</p>
                </div>

                <div className="border-2 border-dashed border-slate-200 rounded-xl p-3 flex items-center justify-center text-slate-400 gap-2 cursor-pointer hover:border-blue-300 hover:text-blue-500 transition-colors">
                  <Plus className="w-4 h-4" />
                  <span className="text-sm font-semibold">Add Next Sentence</span>
                </div>
              </div>

              {/* Player Controls Footer */}
              <div className="p-4 md:p-6 bg-white border-t border-slate-100">
                <div className="flex flex-col sm:flex-row items-center justify-between gap-4 mb-4">
                  <div className="flex items-center gap-2 w-full sm:w-auto justify-between sm:justify-start">
                    <span className="text-xs font-bold text-slate-400 uppercase tracking-wider">Voice</span>
                    <select className="bg-slate-100 border-none text-sm font-semibold text-slate-700 rounded-lg py-1 px-3 cursor-pointer outline-none">
                      <option>ATC - British</option>
                      <option>ATC - US</option>
                    </select>
                  </div>
                  <div className="flex items-center gap-2 w-full sm:w-auto justify-between sm:justify-start">
                    <span className="text-xs font-bold text-slate-400 uppercase tracking-wider">Speed</span>
                    <div className="flex items-center gap-1 bg-slate-100 rounded-lg p-1">
                      <span className="px-2 py-0.5 rounded text-xs font-bold text-slate-500 cursor-pointer hover:bg-white">0.5x</span>
                      <span className="px-2 py-0.5 rounded text-xs font-bold bg-white shadow-sm text-blue-600">1x</span>
                    </div>
                  </div>
                </div>

                <div className="flex justify-center items-center gap-6">
                   <FastForward className="w-6 h-6 text-slate-400 rotate-180 cursor-pointer hover:text-slate-600" />
                   <div className="w-14 h-14 rounded-full bg-[#003049] text-white flex items-center justify-center shadow-lg cursor-pointer hover:scale-105 transition-transform">
                      <Play className="w-6 h-6 ml-1" />
                   </div>
                   <FastForward className="w-6 h-6 text-slate-400 cursor-pointer hover:text-slate-600" />
                </div>
              </div>
            </div>

            {/* Floating Elements - Hidden on mobile, visible on md+ */}
            <motion.div 
              animate={{ y: [0, -10, 0] }}
              transition={{ repeat: Infinity, duration: 4, ease: "easeInOut" }}
              className="hidden md:block absolute -top-6 -right-6 bg-white p-4 rounded-xl shadow-xl border border-slate-100 z-20"
            >
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-full bg-blue-100 flex items-center justify-center text-blue-600">
                  <BookOpen className="w-5 h-5" />
                </div>
                <div>
                  <p className="text-xs text-slate-500 font-bold uppercase">Source</p>
                  <p className="text-sm font-bold text-slate-800">A220 Manual</p>
                </div>
              </div>
            </motion.div>

          </motion.div>
        </div>
      </div>
    </section>
  );
};
